const { Decimal128 } = require("mongodb");
const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const moment = require('moment');

const set_1 = new mongoose.Schema({
    reg_no: String,
    report_year: { type: Number, min:2021, max: 9999 },
    submit_status: { type: Boolean, default: false},
    date_submitted: { type: Date, default: () => moment().toDate() }, 
    schedule_1: {
        cash_on_hand: { type: Number, decimal: true, integer: false, default: null  },
        checks_other_cash_items: { type: Number, decimal: true, integer: false, default: null  },
        cash_in_bank: { type: Number, decimal: true, integer: false, default: null  },
        cash_in_cooperative_federations: { type: Number, decimal: true, integer: false, default: null  },
        petty_cash_fund: { type: Number, decimal: true, integer: false, default: null  },
        revolving_fund: { type: Number, decimal: true, integer: false, default: null  },
        change_fund: { type: Number, decimal: true, integer: false, default: null  },
        atm_fund: { type: Number, decimal: true, integer: false, default: null  },
        total_cash_cash_equivalents: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_2: {
        loans_receivable: {
            current: { type: Number, decimal: true, integer: false, default: null  },
            past_due: { 
                one_30_days: { type: Number, decimal: true, integer: false, default: null  },
                thirty_one_360_days: { type: Number, decimal: true, integer: false, default: null  },
                over_360_days: { type: Number, decimal: true, integer: false, default: null  },
                total_past_due_loans: { type: Number, decimal: true, integer: false, default: null  },
              },
            restructure: { type: Number, decimal: true, integer: false, default: null  },
            loans_litigation: { type: Number, decimal: true, integer: false, default: null  },
            less_unearned_interest_discounts: { type: Number, decimal: true, integer: false, default: null  },
            less_allowance_for_probable_losses_on_loans: { type: Number, decimal: true, integer: false, default: null  },
            net_loans_receivable: { type: Number, decimal: true, integer: false, default: null  },
        },
        account_receivable: {
           current: { type: Number, decimal: true, integer: false, default: null  },
           past_due: {
            one_30_days: { type: Number, decimal: true, integer: false, default: null  },
            thirty_one_360_days: { type: Number, decimal: true, integer: false, default: null  },
            over_360_days: { type: Number, decimal: true, integer: false, default: null  },
            total_past_due_accounts_receivable: { type: Number, decimal: true, integer: false, default: null  },
           },
           restructure: { type: Number, decimal: true, integer: false, default: null  },
           in_litigation: { type: Number, decimal: true, integer: false, default: null  },
           less_allowance_for_probable_losses_on_accounts_receivables: { type: Number, decimal: true, integer: false, default: null  },
           net_accounts_receivable: { type: Number, decimal: true, integer: false, default: null  }, 
        },
        intallment_receivable: {
            current: { type: Number, decimal: true, integer: false, default: null  },
            past_due: { type: Number, decimal: true, integer: false, default: null  },
            restructure: { type: Number, decimal: true, integer: false, default: null  },
            in_litigation: { type: Number, decimal: true, integer: false, default: null  },
            less_allowance_for_probable_losses_on_installment: { type: Number, decimal: true, integer: false, default: null  },
            unrealized_gross_margin: { type: Number, decimal: true, integer: false, default: null  },
        },
        sales_contract_receivable: {
            sale_contract: { type: Number, decimal: true, integer: false, default: null  },
            less_allowance_for_probable_losses_sales_contract: { type: Number, decimal: true, integer: false, default: null  },
            net_sales_contract_receivable: { type: Number, decimal: true, integer: false, default: null  },
        },
        service_receivable: { type: Number, decimal: true, integer: false, default: null  },
        account_receivable_non_trade: { type: Number, decimal: true, integer: false, default: null  },
        advances_officers_emp_members: { type: Number, decimal: true, integer: false, default: null  },
        due_accountable_officers_emp: { type: Number, decimal: true, integer: false, default: null  },
        finance_less_receivable: { type: Number, decimal: true, integer: false, default: null  },
        less_allowance_for_impairment_finance_lease: { type: Number, decimal: true, integer: false, default: null  },
        other_current_receivables: { type: Number, decimal: true, integer: false, default: null  },
        total_loans_receivables: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_3: {
        financial_asset_fair_value_profit_loss: { type: Number, decimal: true, integer: false, default: null  },
        financial_asset_cost: { type: Number, decimal: true, integer: false, default: null  },
        total_financial_assets: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_4: {
        merchandise_inven: { type: Number, decimal: true, integer: false, default: null  },
        repossessed_inven: { type: Number, decimal: true, integer: false, default: null  },
        spare_parts_other_goods_inven: { type: Number, decimal: true, integer: false, default: null  },
        raw_materials_inven: { type: Number, decimal: true, integer: false, default: null  },
        work_process_inven: { type: Number, decimal: true, integer: false, default: null  },
        finished_goods_inven: { type: Number, decimal: true, integer: false, default: null  },
        agri_produce: { type: Number, decimal: true, integer: false, default: null  },
        equipment_lease_inven: { type: Number, decimal: true, integer: false, default: null  },
        less_allowance_impairment: { type: Number, decimal: true, integer: false, default: null  },
        total_inventories: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_5: {
        plants_bio: { type: Number, decimal: true, integer: false, default: null  },
        animals_bio: { type: Number, decimal: true, integer: false, default: null  },
        total_bio: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_6: {
        input_tax: { type: Number, decimal: true, integer: false, default: null  },
        creditable_vat: { type: Number, decimal: true, integer: false, default: null  },
        creditable_witholding: { type: Number, decimal: true, integer: false, default: null  },
        deposit_suppliers: { type: Number, decimal: true, integer: false, default: null  },
        unused_supplies: { type: Number, decimal: true, integer: false, default: null  },
        asset_acqui_settl_loans_acc: { type: Number, decimal: true, integer: false, default: null  },
        less_accu_depreciation_impairment: { type: Number, decimal: true, integer: false, default: null  },
        prepared_expenses: { type: Number, decimal: true, integer: false, default: null  },
        other_current_assets: { type: Number, decimal: true, integer: false, default: null  },
        total_other_current: { type: Number, decimal: true, integer: false, default: null  },
    }
});

const current_assets = mongoose.model("afs_set_1", set_1);


const set_2 = new mongoose.Schema({
    reg_no: String,
    report_year: { type: Number, min:2021, max: 9999 },
    submit_status: { type: Boolean, default: false},
    date_submitted: { type: Date, default: () => moment().toDate() },
    schedule_7: {
        financial_asset_cost: { type: Number, decimal: true, integer: false, default: null  },
        less_allowancoe_impairement: { type: Number, decimal: true, integer: false, default: null  },
        long_term_net: { type: Number, decimal: true, integer: false, default: null  },
        financial_asset_amortized_cost: { type: Number, decimal: true, integer: false, default: null  },
        less_allowance_impairment_amortized: { type: Number, decimal: true, integer: false, default: null  },
        amortized_net: { type: Number, decimal: true, integer: false, default: null  },
        total_financial_instru: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_8: {
        invest_land: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        invest_building: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        ropa: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        total_invest_property: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        }
    },
    schedule_9: {
        land_improvements: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        land: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        building_improvements: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        building_leased_land: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        utility_plant: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        prop_plant_equip_under_finance: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        ffe: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        mte: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        kitchen_canteen_catering_equip: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        transpo_equip: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        linens_uniforms: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        nursery_greenhouse: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        leashold_rights_improvements: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        construction_progress: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        other_property_plant_equip: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        total_property_plant_equip: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            additions: { type: Number, decimal: true, integer: false, default: null  },
            disposal: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            impairment_loss: { type: Number, decimal: true, integer: false, default: null  },
            accumulated_depreciation: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        }
    },
    schedule_10: {
        animals_bio: { type: Number, decimal: true, integer: false, default: null  },
        less_accu_depre_animals: { type: Number, decimal: true, integer: false, default: null  },
        animals_net: { type: Number, decimal: true, integer: false, default: null  },
        plants_bio: { type: Number, decimal: true, integer: false, default: null  },
        less_accu_depre_plants: { type: Number, decimal: true, integer: false, default: null  },
        plants_net: { type: Number, decimal: true, integer: false, default: null  },
        total_bio: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_11: {
        franchise: { type: Number, decimal: true, integer: false, default: null  },
        franchise_cost: { type: Number, decimal: true, integer: false, default: null  },
        copyright: { type: Number, decimal: true, integer: false, default: null  },
        patent: { type: Number, decimal: true, integer: false, default: null  },
        total_intagible: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_12: {
        comput_cost_net: { type: Number, decimal: true, integer: false, default: null  },
        other_fund_depo: { type: Number, decimal: true, integer: false, default: null  },
        finance_lease_receiv: { type: Number, decimal: true, integer: false, default: null  },
        due_from_head_office: { type: Number, decimal: true, integer: false, default: null  },
        deposit_on_returnable_container: { type: Number, decimal: true, integer: false, default: null  },
        misscell_assets: { type: Number, decimal: true, integer: false, default: null  },
        total_other_non_cur_asset: { type: Number, decimal: true, integer: false, default: null  },
    }
});

const non_current_assets = mongoose.model("afs_set_2", set_2);

const set_3 = new mongoose.Schema({
    reg_no: String,
    report_year: { type: Number, min:2021, max: 9999 },
    submit_status: { type: Boolean, default: false},
    date_submitted: { type: Date, default: () => moment().toDate() },
    schedule_13: {
        saving_depost: { type: Number, decimal: true, integer: false, default: null  },
        time_depost: { type: Number, decimal: true, integer: false, default: null  },
        total_deposit_liab: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_14: {
        accounts_trade: { type: Number, decimal: true, integer: false, default: null  },
        accounts_non_trade: { type: Number, decimal: true, integer: false, default: null  },
        loans_pay_current: { type: Number, decimal: true, integer: false, default: null  },
        finance_lease_pay_current: { type: Number, decimal: true, integer: false, default: null  },
        due_deploy_members: { type: Number, decimal: true, integer: false, default: null  },
        cash_bond_payable: { type: Number, decimal: true, integer: false, default: null  },
        other_payable: { type: Number, decimal: true, integer: false, default: null  },
        total_account_other_payables: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_15: {
        due_regulatory_agency: { type: Number, decimal: true, integer: false, default: null  },
        ss_ecc_phil_pagibig_contri: { type: Number, decimal: true, integer: false, default: null  },
        sss_pagibig_loans_pay: { type: Number, decimal: true, integer: false, default: null  },
        withholding_tax_pay: { type: Number, decimal: true, integer: false, default: null  },
        output_tax: { type: Number, decimal: true, integer: false, default: null  },
        vat_pay: { type: Number, decimal: true, integer: false, default: null  },
        income_tax_pay: { type: Number, decimal: true, integer: false, default: null  },
        other_accrued_expenses: { type: Number, decimal: true, integer: false, default: null  },
        total_accrued_expenses: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_16: {
        deposit_customer: { type: Number, decimal: true, integer: false, default: null  },
        advances_customer: { type: Number, decimal: true, integer: false, default: null  },
        school_program_support_fund_pay: { type: Number, decimal: true, integer: false, default: null  },
        intereset_share_capital_pay: { type: Number, decimal: true, integer: false, default: null  },
        patronage_refund_payable: { type: Number, decimal: true, integer: false, default: null  },
        due_union_fed_cetf: { type: Number, decimal: true, integer: false, default: null  },
        other_current_liab: { type: Number, decimal: true, integer: false, default: null  },
        total_other_current_liab: { type: Number, decimal: true, integer: false, default: null  },
    }
});

const liabilities = mongoose.model("afs_set_3", set_3);

const set_4 = new mongoose.Schema({
    reg_no: String,
    report_year: { type: Number, min:2021, max: 9999 },
    submit_status: { type: Boolean, default: false},
    date_submitted: { type: Date, default: () => moment().toDate() },
    schedule_17: {
        loan_pay: { type: Number, decimal: true, integer: false, default: null  },
        less_discount_loans_pay: { type: Number, decimal: true, integer: false, default: null  },
        loans_pay_net: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_18: {
        bonds_pay: { type: Number, decimal: true, integer: false, default: null  },
        add_bond_prem: { type: Number, decimal: true, integer: false, default: null  },
        less_unamortized_bond_discount: { type: Number, decimal: true, integer: false, default: null  },
        bonds_payable_net: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_19: {
        project_subsid_fund: { type: Number, decimal: true, integer: false, default: null  },
        member_benefit_other_fund_pay: { type: Number, decimal: true, integer: false, default: null  },
        due_head_office_branch: { type: Number, decimal: true, integer: false, default: null  },
        other_non_curr_liab: { type: Number, decimal: true, integer: false, default: null  },
        total_other_non_curr_liab: { type: Number, decimal: true, integer: false, default: null  },
    }
});

const non_current_liabilities = mongoose.model("afs_set_4", set_4);

const set_5 = new mongoose.Schema({
    reg_no: String,
    report_year: { type: Number, min:2021, max: 9999 },
    submit_status: { type: Boolean, default: false},
    date_submitted: { type: Date, default: () => moment().toDate() },
    schedule_20: {
        authorized_share_common: { type: Number, decimal: true, integer: false, default: null  },
        par_value_per_share: { type: Number, decimal: true, integer: false, default: null  },
        subscribed_common: { type: Number, decimal: true, integer: false, default: null  },
        paid_up_common: { type: Number, decimal: true, integer: false, default: null  },
        treasury_common: { type: Number, decimal: true, integer: false, default: null  },
        total_paid_up_common: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_21: {
        authorized_share_pref: { type: Number, decimal: true, integer: false, default: null  },
        par_value_per_pref: { type: Number, decimal: true, integer: false, default: null  },
        subscribed_pref: { type: Number, decimal: true, integer: false, default: null  },
        paid_up_pref: { type: Number, decimal: true, integer: false, default: null  },
        treasury_pref: { type: Number, decimal: true, integer: false, default: null  },
        total_paid_up_pref: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_22: {
        reserve_fund: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            current_year_alloc: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            current_year_util: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },

        },
        coop_educ_train_fund: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            current_year_alloc: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            current_year_util: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        commun_dev_fund: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            current_year_alloc: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            current_year_util: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        optional_fund: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            current_year_alloc: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            current_year_util: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        },
        total_statutory_fund: {
            balance_beg: { type: Number, decimal: true, integer: false, default: null  },
            current_year_alloc: { type: Number, decimal: true, integer: false, default: null  },
            total: { type: Number, decimal: true, integer: false, default: null  },
            current_year_util: { type: Number, decimal: true, integer: false, default: null  },
            balance_end: { type: Number, decimal: true, integer: false, default: null  },
        }
    }
});

const member_equity = mongoose.model("afs_set_5", set_5);

const set_6 = new mongoose.Schema({
    reg_no: String,
    report_year: { type: Number, min:2021, max: 9999 },
    submit_status: { type: Boolean, default: false},
    date_submitted: { type: Date, default: () => moment().toDate() },
    schedule_23: {
        interest_income_loans: { type: Number, decimal: true, integer: false, default: null  },
        services_fees: { type: Number, decimal: true, integer: false, default: null  },
        filling_fees: { type: Number, decimal: true, integer: false, default: null  },
        fines_penalties_surcharges: { type: Number, decimal: true, integer: false, default: null  },
        total_income_credit_op: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_24: {
        service_income: { type: Number, decimal: true, integer: false, default: null  },
        interest_income_lease_agree: { type: Number, decimal: true, integer: false, default: null  },
        total_revenues: { type: Number, decimal: true, integer: false, default: null  },
        less_cost_service: { type: Number, decimal: true, integer: false, default: null  },
        gross_rev_service_op: { type: Number, decimal: true, integer: false, default: null  },
        less_operating_expenses: { type: Number, decimal: true, integer: false, default: null  },
        income_service_op: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_25: {
        sales: { type: Number, decimal: true, integer: false, default: null  },
        installment_sales: { type: Number, decimal: true, integer: false, default: null  },
        less_sales_return_allowances: { type: Number, decimal: true, integer: false, default: null  },
        less_sales_discounts: { type: Number, decimal: true, integer: false, default: null  },
        net_sales: { type: Number, decimal: true, integer: false, default: null  },
        less_cost_good_sold: { type: Number, decimal: true, integer: false, default: null  },
        less_gross_margin_market_op: { type: Number, decimal: true, integer: false, default: null  },
        less_operating_expenses: { type: Number, decimal: true, integer: false, default: null  },
        less_income_marketing_op: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_26: {
        sales: { type: Number, decimal: true, integer: false, default: null  },
        less_sales_return_allowances: { type: Number, decimal: true, integer: false, default: null  },
        less_sales_discount: { type: Number, decimal: true, integer: false, default: null  },
        net_sales: { type: Number, decimal: true, integer: false, default: null  },
        less_cost_good_sold: { type: Number, decimal: true, integer: false, default: null  },
        less_gross_margin_consum_catering_op: { type: Number, decimal: true, integer: false, default: null  },
        less_operating_expenses: { type: Number, decimal: true, integer: false, default: null  },
        less_income_consum_catering_op: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_27: {
        sales: { type: Number, decimal: true, integer: false, default: null  },
        less_sales_return_allowances: { type: Number, decimal: true, integer: false, default: null  },
        less_sales_discount: { type: Number, decimal: true, integer: false, default: null  },
        net_sales: { type: Number, decimal: true, integer: false, default: null  },
        less_cost_good_sold: { type: Number, decimal: true, integer: false, default: null  },
        less_gross_margin_production_op: { type: Number, decimal: true, integer: false, default: null  },
        less_operating_expenses: { type: Number, decimal: true, integer: false, default: null  },
        less_income_production_op: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_28: {
        income_interest_invest_deposits: { type: Number, decimal: true, integer: false, default: null  },
        membership_fee: { type: Number, decimal: true, integer: false, default: null  },
        commission_income: { type: Number, decimal: true, integer: false, default: null  },
        realized_gross_margin: { type: Number, decimal: true, integer: false, default: null  },
        misc_income: { type: Number, decimal: true, integer: false, default: null  },
        total_other_income: { type: Number, decimal: true, integer: false, default: null  },
    }
});

const so_revenue = mongoose.model("afs_set_6", set_6);

const set_7 = new mongoose.Schema({
    reg_no: String,
    report_year: { type: Number, min:2021, max: 9999 },
    submit_status: { type: Boolean, default: false},
    date_submitted: { type: Date, default: () => moment().toDate() },
    schedule_29: {
        interest_expense_borrow: { type: Number, decimal: true, integer: false, default: null  },
        interest_expense_deposits: { type: Number, decimal: true, integer: false, default: null  },
        other_finance_charges: { type: Number, decimal: true, integer: false, default: null  },
        total_financing_costs: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_30: {
        advertising_promotion: { type: Number, decimal: true, integer: false, default: null  },
        amortization: { type: Number, decimal: true, integer: false, default: null  },
        amortization_leasehold_rights_improve: { type: Number, decimal: true, integer: false, default: null  },
        breakage_losses_kitchen_equip: { type: Number, decimal: true, integer: false, default: null  },
        comission_expenses: { type: Number, decimal: true, integer: false, default: null  },
        communication: { type: Number, decimal: true, integer: false, default: null  },
        depreciation: { type: Number, decimal: true, integer: false, default: null  },
        employee_benefits: { type: Number, decimal: true, integer: false, default: null  },
        freight_out_delivery_expenses: { type: Number, decimal: true, integer: false, default: null  },
        gas_oil_lubricants: { type: Number, decimal: true, integer: false, default: null  },
        incentives_allowance: { type: Number, decimal: true, integer: false, default: null  },
        insurance: { type: Number, decimal: true, integer: false, default: null  },
        misc_expense: { type: Number, decimal: true, integer: false, default: null  },
        power_light_water: { type: Number, decimal: true, integer: false, default: null  },
        product_service_dev: { type: Number, decimal: true, integer: false, default: null  },
        product_research: { type: Number, decimal: true, integer: false, default: null  },
        product_service_marketing_prom: { type: Number, decimal: true, integer: false, default: null  },
        rentals: { type: Number, decimal: true, integer: false, default: null  },
        repairs_maint: { type: Number, decimal: true, integer: false, default: null  },
        representation: { type: Number, decimal: true, integer: false, default: null  },
        retirement_benefits_expense: { type: Number, decimal: true, integer: false, default: null  },
        royalties: { type: Number, decimal: true, integer: false, default: null  },
        salaries_wages: { type: Number, decimal: true, integer: false, default: null  },
        spoilage_break_losses: { type: Number, decimal: true, integer: false, default: null  },
        sss_philhealth_ecc_pagibig: { type: Number, decimal: true, integer: false, default: null  },
        storage_warehousing_expenses: { type: Number, decimal: true, integer: false, default: null  },
        store_canteen_kitchen_catering_supp: { type: Number, decimal: true, integer: false, default: null  },
        taxes_fees_charges: { type: Number, decimal: true, integer: false, default: null  },
        travel_transportation: { type: Number, decimal: true, integer: false, default: null  },
        total_selling_marketing_cost: { type: Number, decimal: true, integer: false, default: null  },
    },
    schedule_31: {
        affiliation_fee: { type: Number, decimal: true, integer: false, default: null  },
        amortization: { type: Number, decimal: true, integer: false, default: null  },
        amortization_leasehold_rights_improve: { type: Number, decimal: true, integer: false, default: null  },
        bank_charges: { type: Number, decimal: true, integer: false, default: null  },
        certifications_recog: { type: Number, decimal: true, integer: false, default: null  },
        collection_expense: { type: Number, decimal: true, integer: false, default: null  },
        communication: { type: Number, decimal: true, integer: false, default: null  },
        depreciation: { type: Number, decimal: true, integer: false, default: null  },
        employee_benefits: { type: Number, decimal: true, integer: false, default: null  },
        gas_oil_lubricants: { type: Number, decimal: true, integer: false, default: null  },
        gen_assembly_expenses: { type: Number, decimal: true, integer: false, default: null  },
        gen_support_services: { type: Number, decimal: true, integer: false, default: null  },
        impairment_losses: { type: Number, decimal: true, integer: false, default: null  },
        insurance: { type: Number, decimal: true, integer: false, default: null  },
        litigation_expenses: { type: Number, decimal: true, integer: false, default: null  },
        meeting_conferences: { type: Number, decimal: true, integer: false, default: null  },
        members_benefit_expense: { type: Number, decimal: true, integer: false, default: null  },
        misc_expense: { type: Number, decimal: true, integer: false, default: null  },
        office_supplies: { type: Number, decimal: true, integer: false, default: null  },
        officers_honorarium_allowances: { type: Number, decimal: true, integer: false, default: null  },
        periodicals_magazine_subsc: { type: Number, decimal: true, integer: false, default: null  },
        power_light_water: { type: Number, decimal: true, integer: false, default: null  },
        professional_fees: { type: Number, decimal: true, integer: false, default: null  },
        probable_losses_accounts_loans_install_reciev: { type: Number, decimal: true, integer: false, default: null  },
        rentals: { type: Number, decimal: true, integer: false, default: null  },
        repairs_maintenance: { type: Number, decimal: true, integer: false, default: null  },
        representation: { type: Number, decimal: true, integer: false, default: null  },
        retirement_ben_expense: { type: Number, decimal: true, integer: false, default: null  },
        salaries_wages: { type: Number, decimal: true, integer: false, default: null  },
        school_program_support: { type: Number, decimal: true, integer: false, default: null  },
        social_community_service_expense: { type: Number, decimal: true, integer: false, default: null  },
        sss_philhealth_pagibig: { type: Number, decimal: true, integer: false, default: null  },
        taxes_fees_charges: { type: Number, decimal: true, integer: false, default: null  },
        trainings_seminars: { type: Number, decimal: true, integer: false, default: null  },
        travel_transport: { type: Number, decimal: true, integer: false, default: null  },
        total_admin_cost: { type: Number, decimal: true, integer: false, default: null  },
    }
});

const so_expense = mongoose.model("afs_set_7", set_7);

const set_8 = new mongoose.Schema({
    reg_no: String,
    report_year: { type: Number, min:2021, max: 9999 },
    submit_status: { type: Boolean, default: false},
    date_submitted: { type: Date, default: () => moment().toDate() },
    schedule_32: {
        project_subsidy: { type: Number, decimal: true, integer: false, default: null  },
        donation_grand_subsidy: { type: Number, decimal: true, integer: false, default: null  },
        optional_fund_sb: { type: Number, decimal: true, integer: false, default: null  },
        gains_sale_proeprty_equipment: { type: Number, decimal: true, integer: false, default: null  },
        gains_investment: { type: Number, decimal: true, integer: false, default: null  },
        gains_sale_repossessed_item: { type: Number, decimal: true, integer: false, default: null  },
        gains_foreign_exchange_valuation: { type: Number, decimal: true, integer: false, default: null  },
        subsidized_project_expense: { type: Number, decimal: true, integer: false, default: null  },
        losses_sale_property_equip: { type: Number, decimal: true, integer: false, default: null  },
        losses_investment: { type: Number, decimal: true, integer: false, default: null  },
        losses_sale_repossessed_item: { type: Number, decimal: true, integer: false, default: null  },
        losses_foreign_exchange_valuation: { type: Number, decimal: true, integer: false, default: null  },
        prior_year_adjustment: { type: Number, decimal: true, integer: false, default: null  },
        total_other_items: { type: Number, decimal: true, integer: false, default: null  },
    },
});

const so_other_items = mongoose.model("afs_set_8", set_8);


module.exports = { Afs1: current_assets, Afs2: non_current_assets, Afs3: liabilities, Afs4: non_current_liabilities, Afs5: member_equity, Afs6: so_revenue, Afs7: so_expense, Afs8: so_other_items }